"""导出训练好的学生模型 → MCU C 文件 (model_factory 格式, 归一化折叠进权重).

默认读取 runs/kamm533_student.pt (pipeline.py 的产物), 架构从 checkpoint 的
arch 字段自动识别. 生成 nn_model_<arch>_v4.c/.h:

  - polar_encode 输出原始物理量 (v, delta, d, theta), 归一化折叠进第一层权重:
      state_enc.weight[:,0] /= V_MAX(5.0)    [:,1] /= DELTA_MAX
      target_enc.weight[:,0] /= D_SCALE(5.0) [:,1] /= PI
  - 输出钳位走 g_model_active->nn_a_max / nn_a_brake_max / nn_o_max (运行时)
  - 末尾打印 model_desc_t 符号名, 供 model_factory / config.h 注册

用法:
  python export_mcu.py                                  # 默认 runs/kamm533_student.pt
  python export_mcu.py --ckpt runs/xxx.pt --out-dir .   # 指定输入/输出目录
"""
import argparse, os, sys
import numpy as np
import torch

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import pipeline as P

# 固件工程 core/ 目录 (存在则默认写入; 否则用 --out-dir)
MCU = 'C:/Users/tsian/Desktop/beta_ackerman/project/code/core'

# arch → (dims, ckpt 默认值)
ARCHS = {
    'gpmed':   dict(h_state=10, h_tgt=10, h1=64, h2=64, h3=32, cls='GPMedium',
                    name='GP-Medium 9K'),
    'gpsmall': dict(h_state=8,  h_tgt=8,  h1=48, h2=32, h3=16, cls='GPSmall',
                    name='GP-Small 3.7K'),
}
VER_NAME = {'gpmed': 'NN_VER_GPMED_V4', 'gpsmall': 'NN_VER_GPSMALL_V4'}
MODEL_SYM = {'gpmed': 'g_model_gpmed_v4', 'gpsmall': 'g_model_gpsmall_v4'}
FN_NAME = {'gpmed': 'nn_planner_step_gpmed_v4', 'gpsmall': 'nn_planner_step_gpsmall_v4'}
FILE_BASE = {'gpmed': 'nn_model_gpmed_v4', 'gpsmall': 'nn_model_gpsmall_v4'}


def fmt_array(name, data, per_line=8):
    flat = np.asarray(data, dtype=np.float32).ravel()
    out = [f'static const f32 {name}[{len(flat)}] = {{']
    for i in range(0, len(flat), per_line):
        out.append('    ' + ', '.join(f'{v:.8f}f' for v in flat[i:i+per_line]) + ',')
    out.append('};')
    return '\n'.join(out)


def build_c(arch, m, arrays, n_params, ckpt_path, a_lat):
    d = ARCHS[arch]
    hs, ht, h1, h2, h3 = d['h_state'], d['h_tgt'], d['h1'], d['h2'], d['h3']
    cat_dim = hs + 3 * ht
    fn = FN_NAME[arch]; sym = MODEL_SYM[arch]; ver = VER_NAME[arch]
    arch_line = (f'state_enc(2→{hs}) + target_enc(2→{ht})×3 → concat({cat_dim}D) '
                 f'→ {h1}→{h2}→{h3}→2 ReLU')

    return f'''/**
 * {FILE_BASE[arch]}.c — {d['name']} Kamm v4: vst+航点 → [a, omega]
 *
 * Generated by export_mcu_gpmed.py from {ckpt_path}
 * Architecture: polar_8d → {arch_line}
 * Params: {n_params}
 * Kamm asymmetric: a_long=5.0 a_brake=3.0 a_lat={a_lat}
 * 归一化已融合进权重: state_enc÷[5.0, 0.4636], target_enc÷[5.0, π]
 * 训练: v4 分布 (纯半正态截断 [0.05,6.5]), 蒸馏 BC+DAgger×12
 */
#include "config.h"
#if NN_MODEL_VERSION == {ver}
#include "{FILE_BASE[arch]}.h"
#include "model_factory.h"
#include "utils.h"
#include <math.h>

/* ═══ Weights (generated by export_mcu_gpmed.py) ═══ */

{fmt_array('fc_state_w', arrays['fc_state_w'])}
{fmt_array('fc_state_b', arrays['fc_state_b'])}

{fmt_array('fc_tgt_w', arrays['fc_tgt_w'])}
{fmt_array('fc_tgt_b', arrays['fc_tgt_b'])}

{fmt_array('fc1_w', arrays['fc1_w'])}
{fmt_array('fc1_b', arrays['fc1_b'])}

{fmt_array('fc2_w', arrays['fc2_w'])}
{fmt_array('fc2_b', arrays['fc2_b'])}

{fmt_array('fc3_w', arrays['fc3_w'])}
{fmt_array('fc3_b', arrays['fc3_b'])}

{fmt_array('fc4_w', arrays['fc4_w'])}
{fmt_array('fc4_b', arrays['fc4_b'])}

/* ═══ Internal helpers ═══ */

static inline void dense_linear(f32 *out, const f32 *inp, const f32 *w, const f32 *b,
                                int in_dim, int out_dim) {{
    for (int i = 0; i < out_dim; i++) {{
        f32 s = b[i];
        for (int j = 0; j < in_dim; j++) s += w[i*in_dim + j] * inp[j];
        out[i] = s;
    }}
}}

static inline void dense_relu(f32 *out, const f32 *inp, const f32 *w, const f32 *b,
                              int in_dim, int out_dim) {{
    for (int i = 0; i < out_dim; i++) {{
        f32 s = b[i];
        for (int j = 0; j < in_dim; j++) s += w[i*in_dim + j] * inp[j];
        out[i] = (s > 0.0f) ? s : 0.0f;
    }}
}}

static void polar_encode(f32 out[10], const car_state_t *s,
                         const waypoint_t *g1, const waypoint_t *g2, const waypoint_t *g3) {{
    f32 dx1 = g1->x - s->x, dy1 = g1->y - s->y;
    out[0] = s->v;
    out[1] = s->delta;
    out[2] = sqrtf(dx1*dx1 + dy1*dy1);
    out[3] = wrap_pi(atan2f(dy1, dx1) - s->theta);

    if (out[8] > 0.0f) {{
        f32 dx12 = g2->x - g1->x, dy12 = g2->y - g1->y;
        out[4] = sqrtf(dx12*dx12 + dy12*dy12);
        out[5] = wrap_pi(atan2f(dy12, dx12) - atan2f(dy1, dx1));
    }} else {{ out[4] = 0.0f; out[5] = 0.0f; }}

    if (out[9] > 0.0f) {{
        f32 dx23 = g3->x - g2->x, dy23 = g3->y - g2->y;
        out[6] = sqrtf(dx23*dx23 + dy23*dy23);
        out[7] = wrap_pi(atan2f(dy23, dx23) - atan2f(g2->y - g1->y, g2->x - g1->x));
    }} else {{ out[6] = 0.0f; out[7] = 0.0f; }}
}}

static void nn_forward(f32 out[2], const f32 inp[10]) {{
    f32 h_state[NN_H_STATE]; dense_linear(h_state, inp,   fc_state_w, fc_state_b, 2, NN_H_STATE);
    f32 h_t1[NN_H_TGT];      dense_linear(h_t1,    inp+2, fc_tgt_w,   fc_tgt_b,   2, NN_H_TGT);
    f32 h_t2[NN_H_TGT];      dense_linear(h_t2,    inp+4, fc_tgt_w,   fc_tgt_b,   2, NN_H_TGT);
    f32 h_t3[NN_H_TGT];      dense_linear(h_t3,    inp+6, fc_tgt_w,   fc_tgt_b,   2, NN_H_TGT);
    for (int i = 0; i < NN_H_TGT; i++) {{ h_t2[i] *= inp[8]; h_t3[i] *= inp[9]; }}
    f32 cat[NN_CAT];
    for (int i = 0; i < NN_H_STATE; i++) cat[i] = h_state[i];
    for (int i = 0; i < NN_H_TGT;   i++) cat[NN_H_STATE + i]               = h_t1[i];
    for (int i = 0; i < NN_H_TGT;   i++) cat[NN_H_STATE + NN_H_TGT + i]    = h_t2[i];
    for (int i = 0; i < NN_H_TGT;   i++) cat[NN_H_STATE + 2*NN_H_TGT + i]  = h_t3[i];
    f32 h1[NN_H1]; dense_relu(h1, cat, fc1_w, fc1_b, NN_CAT, NN_H1);
    f32 h2[NN_H2]; dense_relu(h2, h1,  fc2_w, fc2_b, NN_H1, NN_H2);
    f32 h3[NN_H3]; dense_relu(h3, h2,  fc3_w, fc3_b, NN_H2, NN_H3);
    dense_linear(out, h3, fc4_w, fc4_b, NN_H3, 2);
    if (out[0] >  g_model_active->nn_a_max)       out[0] =  g_model_active->nn_a_max;
    if (out[0] < -g_model_active->nn_a_brake_max) out[0] = -g_model_active->nn_a_brake_max;
    if (out[1] >  g_model_active->nn_o_max)       out[1] =  g_model_active->nn_o_max;
    if (out[1] < -g_model_active->nn_o_max)       out[1] = -g_model_active->nn_o_max;
}}

void {fn}(f32 out[2], const car_state_t *vst,
          const waypoint_t *g1, const waypoint_t *g2, const waypoint_t *g3,
          f32 v2, f32 v3) {{
    f32 inp[10];
    inp[8] = v2; inp[9] = v3;
    polar_encode(inp, vst, g1, g2, g3);
    nn_forward(out, inp);
}}

const model_desc_t {sym} = {{
    .forward       = {fn},
    .a_long_max    = 5.0f,
    .a_brake_max   = 3.0f,
    .a_lat_max     = {a_lat}f,
    .v_max         = 5.0f,
    .nn_a_max      = 5.0f,
    .nn_a_brake_max = 3.0f,
    .nn_o_max      = 14.0f,
}};
#endif /* NN_MODEL_VERSION == {ver} */
'''


def build_h(arch, n_params, ckpt_path, a_lat):
    d = ARCHS[arch]
    hs, ht, h1, h2, h3 = d['h_state'], d['h_tgt'], d['h1'], d['h2'], d['h3']
    cat_dim = hs + 3 * ht
    guard = FILE_BASE[arch].upper() + '_H'
    return f'''/**
 * {FILE_BASE[arch]}.h — {d['name']} Kamm v4: polar_8d + GatedConcat
 *
 * Architecture:
 *   state_enc(2→{hs}) + target_enc(2→{ht})×3 → concat({cat_dim}D) → {h1}→{h2}→{h3}→2 ReLU
 *   No input normalization — polar encoding IS the normalization
 *   (scale 已折叠进第一层权重)
 * Params: {n_params}  |  a_lat={a_lat}  |  from {ckpt_path}
 */
#ifndef {guard}
#define {guard}
#include "common.h"

#define NN_IN_DIM    {cat_dim}
#define NN_H_STATE   {hs}
#define NN_H_TGT     {ht}
#define NN_H1        {h1}
#define NN_H2        {h2}
#define NN_H3        {h3}
#define NN_CAT       {cat_dim}
#define NN_OUT_DIM   2

void {FN_NAME[arch]}(f32 out[2], const car_state_t *vst,
                     const waypoint_t *g1, const waypoint_t *g2, const waypoint_t *g3,
                     f32 v2, f32 v3);

#endif
'''


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--ckpt', default='runs/kamm533_student.pt')
    ap.add_argument('--arch', default=None, choices=list(ARCHS), help='默认按 ckpt arch 字段')
    ap.add_argument('--a-lat', type=float, default=P.A_LAT,
                    help='写入 model_desc 的横向约束 (默认取 pipeline.A_LAT, 必须与训练一致)')
    ap.add_argument('--out-dir', default=MCU)
    args = ap.parse_args()

    if not os.path.exists(args.ckpt):
        raise SystemExit(f'{args.ckpt} 不存在 — 先跑 python pipeline.py')
    out_dir = args.out_dir
    if not os.path.isdir(out_dir):
        print(f'(输出目录不存在: {out_dir} → 改用当前目录)')
        out_dir = '.'

    ck = torch.load(args.ckpt, map_location='cpu', weights_only=False)
    arch = args.arch or ck.get('arch')
    if arch not in ARCHS:
        raise SystemExit(f'checkpoint 缺 arch 字段或值未知 ({arch}); 用 --arch 指定')
    d = ARCHS[arch]
    m = getattr(P, d['cls'])(); m.load_state_dict(ck['model_state_dict']); m.eval()

    V_SCALE, D_SCALE, DELTA_MAX = P.V_MAX, P.D_SCALE, P.DELTA_MAX
    w_state = m.state_enc.weight.detach().cpu().numpy().copy()
    w_state[:, 0] /= V_SCALE; w_state[:, 1] /= DELTA_MAX
    w_tgt = m.target_enc.weight.detach().cpu().numpy().copy()
    w_tgt[:, 0] /= D_SCALE; w_tgt[:, 1] /= np.pi

    g = lambda mod, k: getattr(mod, k).detach().cpu().numpy()
    arrays = {
        'fc_state_w': w_state,          'fc_state_b': g(m.state_enc, 'bias'),
        'fc_tgt_w':   w_tgt,            'fc_tgt_b':   g(m.target_enc, 'bias'),
        'fc1_w': g(m.fc1, 'weight'), 'fc1_b': g(m.fc1, 'bias'),
        'fc2_w': g(m.fc2, 'weight'), 'fc2_b': g(m.fc2, 'bias'),
        'fc3_w': g(m.fc3, 'weight'), 'fc3_b': g(m.fc3, 'bias'),
        'fc4_w': g(m.fc4, 'weight'), 'fc4_b': g(m.fc4, 'bias'),
    }
    n_params = sum(v.size for v in arrays.values())

    c_src = build_c(arch, m, arrays, n_params, args.ckpt, args.a_lat)
    h_src = build_h(arch, n_params, args.ckpt, args.a_lat)
    c_path = os.path.join(out_dir, FILE_BASE[arch] + '.c')
    h_path = os.path.join(out_dir, FILE_BASE[arch] + '.h')
    with open(c_path, 'w', encoding='utf-8') as f: f.write(c_src)
    with open(h_path, 'w', encoding='utf-8') as f: f.write(h_src)
    print(f'Written: {c_path} ({n_params} params, arch={arch}, a_lat={args.a_lat})')
    print(f'Written: {h_path}')

    # ── 数值验证: pipeline deploy (归一化) vs 折叠权重的 numpy 前向 (原始物理量) ──
    print('\nVerifying numerical equivalence (folded-weights numpy vs pipeline deploy)...')
    rng = np.random.RandomState(7)
    max_err = 0.0
    for t in range(20):
        v = rng.uniform(0, 5); dlt = rng.uniform(-DELTA_MAX, DELTA_MAX)
        th = rng.uniform(-np.pi, np.pi)
        gs = [np.array([rng.uniform(P.M, P.FLD-P.M), rng.uniform(P.M, P.FLD-P.M)]) for _ in range(3)]
        sp = np.array([P.CAR_X, P.CAR_Y, th, v, dlt], dtype=np.float32)
        px, py = sp[0], sp[1]
        raw = np.zeros(10)
        dx1, dy1 = gs[0][0]-px, gs[0][1]-py
        raw[0] = v; raw[1] = dlt
        raw[2] = np.hypot(dx1, dy1)
        raw[3] = np.arctan2(np.sin(np.arctan2(dy1, dx1) - th), np.cos(np.arctan2(dy1, dx1) - th))
        for k, (a, b) in enumerate(((0, 1), (1, 2))):
            dx, dy = gs[b][0]-gs[a][0], gs[b][1]-gs[a][1]
            raw[4+2*k] = np.hypot(dx, dy)
            h1_ = np.arctan2(gs[1][1]-gs[0][1], gs[1][0]-gs[0][0])
            h0_ = np.arctan2(dy1, dx1)
            ref = h0_ if k == 0 else h1_
            raw[5+2*k] = np.arctan2(np.sin(np.arctan2(dy, dx)-ref), np.cos(np.arctan2(dy, dx)-ref))
        raw[8] = raw[9] = 1.0
        # C 侧前向 (折叠权重, 原始输入)
        hs = arrays['fc_state_w'] @ raw[:2] + arrays['fc_state_b']
        h1 = arrays['fc_tgt_w'] @ raw[2:4] + arrays['fc_tgt_b']
        h2 = arrays['fc_tgt_w'] @ raw[4:6] + arrays['fc_tgt_b']
        h3 = arrays['fc_tgt_w'] @ raw[6:8] + arrays['fc_tgt_b']
        cat = np.concatenate([hs, h1, h2, h3])
        z = np.maximum(arrays['fc1_w'] @ cat + arrays['fc1_b'], 0)
        z = np.maximum(arrays['fc2_w'] @ z + arrays['fc2_b'], 0)
        z = np.maximum(arrays['fc3_w'] @ z + arrays['fc3_b'], 0)
        c_out = arrays['fc4_w'] @ z + arrays['fc4_b']
        c_out[0] = np.clip(c_out[0], -P.A_BRAKE, P.A_LONG); c_out[1] = np.clip(c_out[1], -P.O_MAX, P.O_MAX)
        # pipeline 侧
        p8 = P.polar_8d(torch.tensor(sp[None]), torch.tensor(gs[0][None], dtype=torch.float32),
                        torch.tensor(gs[1][None], dtype=torch.float32), torch.tensor(gs[2][None], dtype=torch.float32))
        with torch.no_grad():
            py_out = m.deploy(p8, torch.tensor([1.]), torch.tensor([1.]))[0].numpy()
        err = float(np.abs(c_out - py_out).max()); max_err = max(max_err, err)
    print(f'Max |Δ| = {max_err:.2e}  {"PASS" if max_err < 1e-4 else "FAIL"}')
    print(f'\n固件登记 (一次性, 每个新模型一次):')
    print(f'  config.h         : #define {VER_NAME[arch]} 404 + include 分支')
    print(f'  model_factory.h  : extern const model_desc_t {MODEL_SYM[arch]};')
    print(f'  planner.c        : g_model_active = &{MODEL_SYM[arch]};')
    print(f'  (IAR .ewp)       : 把 {FILE_BASE[arch]}.c/.h 加入工程')
    print(f'\n注意 a_lat_max={args.a_lat} 写入 model_desc, kinematics.c 用它做运行时摩擦圆/'
          f'转角上限 — 必须与训练时 pipeline.A_LAT({P.A_LAT}) 一致。')


if __name__ == '__main__':
    main()
